config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  mount ShopifyApp::Engine, at: '/'
  resources :product_settings, only: [:update, :edit]
  resources :test_admins
  resources :test_proxies

  namespace :app_proxy do
    root action: 'index'
    get 'index', to: 'index'
  end

  get '/apps/products', as: :proxy_prod
  get '/app_proxy/index/:id', as: :collect_prod, to: 'app_proxy#index'

  get 'all_products', to: 'home#products', as: :all_products
  get '/products/sync', to: 'product_settings#sync', as: :sync_products

  get '/example', to: 'test_admins#example', as: :example

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < AuthenticatedController
  def index
    @products = Product.all
    # @products = ProductSearch.new(product_params).search
    # @webhooks = ShopifyAPI::Webhook.find(:all)
    @vendor_array = ['Adidas', 'American Sports Teams','Aquascutum','Armani','Asics', 'Avirex', 'Barbour', 'Belstaff', 'Best Company', 'Burberry', 'Nike']
    @size_array = ['L', 'M', 'S', "Women's", 'XL', 'XS', 'XXL', 'XXS']
    @product_type = ['Bags', 'dress', 'Football shirts', 'Hockey Top', 'Jackets & Coats', 'Jeans', 'Party Shirts', 'Polo Shirts', 'Rugby Tops', 'Shirts', 'Shorts', 'Skirts', 'Sweatshirts & Hoods', 'T-Shirts', 'Tracksuit', 'Tracksuit Bottoms', 'Trainers', 'Vests', 'Wholesale']
    @price_ranges = ['0 - 31', '31 - 70', '71 - 90', '91 - 110']
  end

  def products
    page = params[:page]
    # @products = ShopifyAPI::Product.find(:all, params: { limit: 36, page: page })
    @products = ProductSearch.new(product_params).search
    @products = [] if products_are_already_in_view?
    render json: {productsPartial: render_to_string('home/_products', locals: {showFirst: false}), layout: false, productCount: @products.count, lastProductID: @products.last.try(:id)}
  end



  private

  def product_params
    {limit: 36, title: params[:brand], product_type: params[:product_type], tag: params[:size], page: params[:page]}
  end

  def products_are_already_in_view?
    params[:last_prod_id].present? && params[:last_prod_id] == @products.last.id.to_s rescue false
  end
end

app/views/home/_product_fields.html.slim
.single-product-container
  - if params[:q]
    .the-modal
      .row.row-style
        .the-modal-sub.medium-8.small-12large-8 style="background-image: url('#{product.first_image_url}'); background-size: cover"
        .the-modal-sub-two.medium-4.small-12.large-4
          .model-close &times;
          .prod-attr = product.vendor
          .prod-attr__small = product.title
          div style="display: flex; align-items: center; margin: 0.5rem 0; line-height: 22px"
            .prod-attr__price = "£ #{product.display_price} GBP"
            - if product.compare_at_price != 0.0
              .prod-attr__small style="font-size: 22px; margin: 0" = "£ #{product.compare_at_display_price}"
          .prod-attr__small Size guide
          .select-box
            .prod-attr__small style="margin-right: 1rem" Size
            select style="border-radius: 5px; width: 100%"
              - product.sizes.each do |size|
                option value="#{size.shopify_id}" = size.title
          div style="display: flex; align-items: center"
            = link_to 'Add to Cart', 'javascript:void(0)', class: 'button js-cart-btn', style: 'background-color: #000000; width: 100%;font-size: 17px;font-weight: bold;'
          .shopify-info-block
            = product.body_html.try(:html_safe)
          p.js-cart-error style="color: red"

  .blur-div
      = link_to "/products/#{product.slug_url}" do
        - if product.quantity <= 0
          div style="background: black;height: 23px;position: absolute; padding: 6px"
           span style="color: white" Sold Out
        .img-container
          .product-image style="background-image: url('#{product.first_image_url}')" value='#{product.id}'
          .product-image-two style="display: none; background-image: url('#{product.second_image_url}')"
      - if params[:q]
        .quick-view-button
          span.quick-view-text QUICK VIEW
      = link_to "/products/#{product.slug_url}" do
        .vendor-field = product.vendor
        .title-container
          .title-field = product.title
        .price-container
          - if product.quantity > 0
            div class="price-field #{product.compare_at_price != 0.0 ? 'new-sale' : ''}" = "£ #{product.display_price} GBP"
            - if product.compare_at_price != 0.0
              .compare-at-price = "£ #{product.compare_at_display_price}"
          - else
            div class="price-field" style="font-weight: 300; color: black" Sold Out

app/views/home/_products.html.slim
.row.div-style style="max-width: 100% #{ProductSetting.last.true_filter_on ? '' : ';padding: 0 !important'}"
  - if @products.any?
    - @products.each do |product|
      .columns.medium-4.small-6.large-3 style="margin-bottom: 46px" class="js-product-group js-product-id-#{product.id}"
        = render partial: 'home/product_fields', locals: {product: product}
  - elsif params[:page].nil?
    .search-result-empty
      p.search-result-empty-text NO RESULTS FOUND

app/views/home/_search_results.html.slim
.search-result-main-container
  .search-result-product-container
    .search-result-product-text PRODUCTS
  - if ProductSetting.last.overflow_scroll_on
    .search-result-main-box style="overflow: auto"
      - @products.each do |product|
        a.search-result-single-box  href="/products/#{product.slug_url}"
          div style="background-image: url('#{product.first_image_url}'); background-size: cover; background-position: center; height: 50px; width: 50px"
          .search-result-sub-container style="margin-left: 0.5rem"
            .search-result-vendor style="font-weight: bold" = product.vendor
            .search-result-title = truncate("#{product.title}", length: 45)
            .search-result-price = "£ #{product.display_price} GBP"
  - else
    .search-result-main-box style="overflow: hidden;"
      - @products.each do |product|
        a.search-result-single-box href="/products/#{product.slug_url}"
          div style="background-image: url('#{product.first_image_url}'); background-size: cover; background-position: center; height: 50px; width: 50px"
          .search-result-sub-container style="margin-left: 0.5rem"
            .search-result-vendor style="font-weight: bold" = product.vendor
            .search-result-title = truncate("#{product.title}", length: 45)
            .search-result-price = "£ #{product.display_price} GBP"
  - if ProductSetting.last.related_search_on
    .search-result-product-container
      .search-result-product-text POPULAR SEARCHES
      br
      .popular-search-container
        - @popular.each do |prod|
          a.pop-search-sub-container href="/products/#{prod.slug_url}"
            .popular-search-icon
            .pop-search-sub-text  = prod.title

app/views/home/index.html.slim
= content_for :javascript do
  javascript:
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({ title: "Home"});
    });
= simple_form_for :product_setting, url: product_setting_path(ProductSetting.last.id), method: :put do |f|
  .admin-section-container
    .admin-section-header-container
      .admin-section-header True search admin
    .row
      .admin-section-side-bar-container.columns.medium-2 style="padding: 0"
        .js-true-search-option style='border-left: 5px solid rgb(92, 106, 196); background-color: white; color: rgb(92, 106, 196);'
          = image_tag('search.svg', size: '20', style: 'margin: 0.5rem')
          .admin-section-side-bar-text True search
      .js-admin-section-search-config-container.columns.medium-10
        .header-box
          span True search
          span The following configurations relate to the True search app
          = link_to 'Sync Products', sync_products_path, class: 'button', style: 'margin: 0; background-color: #3f4eae; border-radius: 5px'
        .filter-app-config-container
          .toggle-switch style="margin-top: 1rem"
            label.switch
              - if ProductSetting.last.true_search_on
                input class="boolean optional" type="checkbox" checked="checked" onclick="$('#product_setting_true_search_on').val() == '1' ? $('#product_setting_true_search_on').val('0') : $('#product_setting_true_search_on').val('1')"
              - else
                input class="boolean optional" type="checkbox" onclick="$('#product_setting_true_search_on').val() == '1' ? $('#product_setting_true_search_on').val('0') : $('#product_setting_true_search_on').val('1')"
              span.slider.round
            .toggle-switch-text True Search Active
            = f.input :true_search_on, as: :hidden, input_html: { value: "#{ProductSetting.last.true_search_on ? '1' : '0'}" }
          hr
          .toggle-switch
            label.switch
              - if ProductSetting.last.include_out_of_stock_products
                input class="boolean optional" type="checkbox" checked="checked" onclick="$('#product_setting_include_out_of_stock_products').val() == '1' ? $('#product_setting_include_out_of_stock_products').val('0') : $('#product_setting_include_out_of_stock_products').val('1')"
              - else
                input class="boolean optional" type="checkbox" onclick="$('#product_setting_include_out_of_stock_products').val() == '1' ? $('#product_setting_include_out_of_stock_products').val('0') : $('#product_setting_include_out_of_stock_products').val('1')"
              span.slider.round
            .toggle-switch-text Include out of stock products
            = f.input :include_out_of_stock_products, as: :hidden, input_html: { value: "#{ProductSetting.last.include_out_of_stock_products ? '1' : '0'}" }

          .toggle-switch style="margin-top: 1rem"
            label.switch
              - if ProductSetting.last.related_search_on
                input class="boolean optional" type="checkbox" checked="checked" onclick="$('#product_setting_related_search_on').val() == '1' ? $('#product_setting_related_search_on').val('0') : $('#product_setting_related_search_on').val('1')"
              - else
                input class="boolean optional" type="checkbox" onclick="$('#product_setting_related_search_on').val() == '1' ? $('#product_setting_related_search_on').val('0') : $('#product_setting_related_search_on').val('1')"
              span.slider.round
            .toggle-switch-text Toggle related search
            = f.input :related_search_on, as: :hidden, input_html: { value: "#{ProductSetting.last.related_search_on ? '1' : '0'}" }

          .toggle-switch style="margin-top: 1rem"
            label.switch
              - if ProductSetting.last.overflow_scroll_on
                input class="boolean optional" type="checkbox" checked="checked" onclick="$('#product_setting_overflow_scroll_on').val() == '1' ? $('#product_setting_overflow_scroll_on').val('0') : $('#product_setting_overflow_scroll_on').val('1')"
              - else
                input class="boolean optional" type="checkbox" onclick="$('#product_setting_overflow_scroll_on').val() == '1' ? $('#product_setting_overflow_scroll_on').val('0') : $('#product_setting_overflow_scroll_on').val('1')"
              span.slider.round
            .toggle-switch-text Toggle overflow scroll on products searched
            = f.input :overflow_scroll_on, as: :hidden, input_html: { value: "#{ProductSetting.last.overflow_scroll_on ? '1' : '0'}" }

          .synonym-container
            = f.simple_fields_for :product_synonyms do |p|
              .js-syn-container
                - ProductSetting.last.product_synonyms.each do |ps|
                  .row
                    .columns.medium-6.small-6.large-6
                      = p.input :synonym, label: false, placeholder: 'Synonym', required: false, input_html: {name: 'product_setting[product_synonyms][synonym][]', value: ps.synonym, style: 'border-radius: 5px'}
                    .columns.medium-6.small-6.large-6
                      = p.input :value, label: false, placeholder: 'Lookup Value', required: false, input_html: {name: 'product_setting[product_synonyms][value][]', value: ps.value, style: 'border-radius: 5px'}
                      = p.input :id, as: :hidden, input_html: { value: ps.id, name: 'product_setting[product_synonyms][id][]' }
                .js-new-syn
                  .row
                    .columns.medium-6.small-6.large-6
                      = p.input :synonym, label: false, placeholder: 'Synonym', required: false, input_html: {name: 'product_setting[product_synonyms][synonym][]', style: 'border-radius: 5px', class: 'js-syn-field'}
                    .columns.medium-6.small-6.large-6
                      = p.input :value, label: false, placeholder: 'Lookup Value', required: false, input_html: {name: 'product_setting[product_synonyms][value][]', style: 'border-radius: 5px', class: 'js-syn-field'}
          = link_to 'Add new synonym', 'javascript:void(0)', class: 'button js-new-syn-button', style: 'width: 230px'

          = f.submit 'Submit', class: 'button' ,style: 'width: 50%; border-radius: 5px; background-color: #3f4eae; display: block'