config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  mount ShopifyApp::Engine, at: '/'
  resources :product_settings, only: [:update, :edit]
  resources :test_admins
  resources :test_proxies

  namespace :app_proxy do
    root action: 'index'
    get 'index', to: 'index'
  end

  get '/apps/products', as: :proxy_prod
  get '/app_proxy/index/:id', as: :collect_prod, to: 'app_proxy#index'

  get 'all_products', to: 'home#products', as: :all_products
  get '/products/sync', to: 'product_settings#sync', as: :sync_products

  get '/example', to: 'test_admins#example', as: :example

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/app_proxy_controller.rb
class AppProxyController < ApplicationController
   include ShopifyApp::AppProxyVerification

  def index
    if params[:search_on_query].present?
      render_search_on_bool
    elsif params[:filter].present?
      render_filtered_products
    elsif params[:search].present?
      render_searched_products
    else
      render_all_products
    end
  end

  private

  def render_search_on_bool
    render json: {search_on: ProductSetting.last.true_search_on}
  end

  def render_all_products
    @products = ProductFilter.new(product_params).filter(query_string)
    @products_count = ProductFilter.new(product_params).count_from_filter(query_string)
    @collection = Collection.find_by_handle(handle_for_collection)
    @vendor_array = all_vendors_for_query
    @size_array = Filter.sizes.pluck(:title)
    @product_type = Filter.types.pluck(:title)
    @price_ranges = ['0 - 31', '31 - 70', '71 - 90', '91 - 110']
    @colours = Filter.colours.pluck(:title)
    @filter_present = filter_present?
    render content_type: 'application/liquid'
  end

  def all_vendors_for_query
    return Filter.brands.pluck(:title) unless params[:q].present?
    vendors = []
    query_arr = params[:q].split(' ')
    query_arr.each do |arr|
      vendors << Product.where('lower(vendor) ~* ?', arr.gsub("*", "").downcase).pluck(:vendor).uniq
    end
    vendors.flatten.present? ? vendors.flatten : Filter.brands.pluck(:title)
  end

  def render_filtered_products
    page = params[:page]
    @products = ProductFilter.new(product_params).filter(query_string)
    @products_count = ProductFilter.new(product_params).count_from_filter(query_string)
    @products = [] if products_are_already_in_view?
    render json: {productsPartial: render_to_string('home/_products', locals: {showFirst: false},layout: false), productCount: @products.count, lastProductID: @products.last.try(:id)}
  end

  def render_searched_products
    @products = ProductFilter.new({title: query_string}).search
    @popular = ProductFilter.new({title: query_string}).popular
    render json: {searchPartial: render_to_string('home/_search_results', layout: false) }
  end

  def query_string
    query_str = params[:q].gsub("*", "") rescue ""
    synon = ProductSetting.last.product_synonyms.where('synonym = ?', query_str).first
    return query_str unless synon
    return synon.value
  end

  def filter_present?
    params[:brand].present? || params[:product_type].present? || params[:size].present? || params[:price].present? || params[:q].present?
  end

  def product_params
    {limit: 36, title: params[:brand], product_type: params[:product_type], tag: params[:size], page: params[:page], price: params[:price], sort_by: params[:sort_by], colour: params[:colour], collection: handle_for_collection}
  end

  def products_are_already_in_view?
    params[:last_prod_id].present? && params[:last_prod_id] == @products.last.id.to_s rescue false
  end

end

app/views/app_proxy/_brand.html.slim
- if desktop
  .filter-brand-container.hidden-on-small-screen
    .heading-container
      .filter-brand-heading BRAND
      .js-brand-filter-icon.js-show-brand-filter
    .filter-brand-collection.js-brand-container.scroll-filter
      - @vendor_array.each do |va|
        - brand = [va] << params[:brand]
        = link_to proxy_prod_path(brand: brand.compact.flatten.uniq, size: params[:size], product_type: params[:product_type], price: params[:price], q: params[:q], collection: handle_for_collection) do
          - if params[:brand] && params[:brand].include?(va)
            .black-box-container
              .black-box-parent style='position: relative'
                .black-box style='position: relative; top: 0; left: 0'
                .small-black-box style='position: absolute; top: 0; left: 0'
              .sub-heading = va
          - else
            .black-box-container
              .black-box
              .sub-heading = va

- else
  .filter-brand-container
    .heading-container
      .filter-brand-heading style='color: white' BRAND
      .js-brand-filter-icon.js-show-brand-filter.filter-icon-minus
    .filter-brand-collection.js-brand-container.scroll-filter
      - @vendor_array.each do |va|
          - brand = [va] << params[:brand]
          = link_to proxy_prod_path(brand: brand.compact.flatten.uniq, size: params[:size], product_type: params[:product_type], price: params[:price], q: params[:q], collection: handle_for_collection) do
            - if params[:brand] && params[:brand].include?(va)
              .black-box-container
                .black-box-parent style='position: relative'
                  .black-box style='position: relative; top: 0; left: 0'
                  .small-black-box style='position: absolute; top: 0; left: 0'
                .sub-heading style='color: white' = va
                .tick-icon
            - else
              .black-box-container
                .black-box
                .sub-heading style='color: white' = va

app/views/app_proxy/_colour.html.slim
- if desktop
  .filter-colour-container.hidden-on-small-screen
    .heading-container
      .filter-colour-heading COLOUR
      .js-colour-filter-icon.js-show-colour-filter
    .filter-colour-collection.js-colour-container.scroll-filter
      - @colours.each do |va|
        - colour = [va] << params[:colour]
        = link_to proxy_prod_path(colour: colour.compact.flatten.uniq, size: params[:size], product_type: params[:product_type], price: params[:price], q: params[:q], brand: params[:brand], collection: handle_for_collection) do
          - if params[:colour] && params[:colour].include?(va)
            .black-box-container
              .black-box-parent style='position: relative'
                .black-box style='position: relative; top: 0; left: 0'
                .small-black-box style='position: absolute; top: 0; left: 0'
              .sub-heading = va
          - else
            .black-box-container
              .black-box
              .sub-heading = va

- else
  .filter-colour-container
    .heading-container
      .filter-colour-heading style='color: white' COLOUR
      .js-colour-filter-icon.js-show-colour-filter.filter-icon-minus
    .filter-colour-collection.js-colour-container
      - @colours.each do |va|
          - colour = [va] << params[:colour]
          = link_to proxy_prod_path(colour: colour.compact.flatten.uniq, size: params[:size], product_type: params[:product_type], price: params[:price], q: params[:q], brand: params[:brand], collection: handle_for_collection) do
          - if params[:colour] && params[:colour].include?(va)
            .black-box-container
              .black-box-parent style='position: relative'
                .black-box style='position: relative; top: 0; left: 0'
                .small-black-box style='position: absolute; top: 0; left: 0'
              .sub-heading style='color: white' = va
              .tick-icon
          - else
            .black-box-container
              .black-box
              .sub-heading style='color: white' = va

app/views/app_proxy/_price.html.slim
- if desktop
  .price-range-container
    div
      .heading-container
        span for="amount-two" style=" font-weight: bold; font-size: 14px" PRICE RANGE:
        .js-price-filter-icon.js-show-price-filter
      div.js-price-container
        input#amount-two readonly="" style="border:0; color: #fe89b5; font-weight:bold; box-shadow: none; background-color: #fefefe; padding-left: 0rem" type="text"
      div.js-price-container
        #slider-range-two
        .price-range-submit
          = link_to 'Filter Price', 'javascript:void(0)', class: 'button js-filter-price', style: 'background: black; width: 100%'
- else
  .price-range-container
    div
      .heading-container
        span style="color: white; font-weight: bold; font-size: 14px" for="amount"  PRICE RANGE:
        .js-price-filter-icon.js-show-price-filter.filter-icon-minus
      div.js-price-container
        input#amount readonly="" style="border:0; color: #fe89b5; font-weight:bold; background-color: #111111; box-shadow: none; padding-left: 0rem" type="text"
      div.js-price-container
        #slider-range
        .price-range-submit
          = link_to 'Filter Price', 'javascript:void(0)', class: 'button js-filter-price-mobile', style: 'background: white; width: 100%'

app/views/app_proxy/_size.html.slim
- if desktop
  .filter-size-container.hidden-on-small-screen
    .heading-container
      .filter-size-heading SIZE
      .js-size-filter-icon.js-show-size-filter
    .filter-size-collection.js-size-container.scroll-filter
      - @size_array.each do |size|
        - multisize = [size] << params[:size]
        = link_to proxy_prod_path(size: multisize.compact.flatten.uniq, brand: params[:brand], product_type: params[:product_type], price: params[:price], q: params[:q], collection: handle_for_collection) do
          - if params[:size] && params[:size].include?(size)
            .black-box-container
              .black-box-parent style='position: relative'
                .black-box style='position: relative; top: 0; left: 0'
                .small-black-box style='position: absolute; top: 0; left: 0'
              .sub-heading = size
          - else
            .black-box-container
              .black-box
              .sub-heading = size
- else
  .filter-size-container
    .heading-container
      .filter-size-heading style='color: white' SIZE
      .js-size-filter-icon.js-show-size-filter.filter-icon-minus
    .filter-size-collection.js-size-container.scroll-filter
      - @size_array.each do |size|
          - multisize = [size] << params[:size]
          = link_to proxy_prod_path(size: multisize.compact.flatten.uniq, brand: params[:brand], product_type: params[:product_type], price: params[:price], q: params[:q], collection: handle_for_collection) do
            - if params[:size] && params[:size].include?(size)
              .black-box-container
                .black-box-parent style='position: relative'
                  .black-box style='position: relative; top: 0; left: 0'
                  .small-black-box style='position: absolute; top: 0; left: 0'
                .sub-heading style='color: white' = size
                .tick-icon
            - else
              .black-box-container
                .black-box
                .sub-heading  style='color: white' = size

app/views/app_proxy/_type.html.slim
- if desktop
  .filter-type-container.hidden-on-small-screen
    .heading-container
      .filter-type-heading TYPE
      .js-type-filter-icon.js-show-type-filter
    .filter-type-collection.js-type-container.scroll-filter
      - @product_type.each do |pt|
        - prodtype = [pt] << params[:product_type]
        = link_to proxy_prod_path(size: params[:size], brand: params[:brand], product_type: prodtype.compact.flatten.uniq, price: params[:price], q: params[:q], collection: handle_for_collection) do
          - if params[:product_type] && params[:product_type].include?(pt)
            .black-box-container
              .black-box-parent style='position: relative'
                .black-box style='position: relative; top: 0; left: 0'
                .small-black-box style='position: absolute; top: 0; left: 0'
              .sub-heading = pt
          - else
            .black-box-container
              .black-box
              .sub-heading = pt

- else
  .filter-type-container
    .heading-container
      .filter-type-heading style='color: white' TYPE
      .js-type-filter-icon.js-show-type-filter.filter-icon-minus
    .filter-type-collection.js-type-container.scroll-filter
      - @product_type.each do |pt|
          - prodtype = [pt] << params[:product_type]
          = link_to proxy_prod_path(size: params[:size], brand: params[:brand], product_type: prodtype.compact.flatten.uniq, price: params[:price], q: params[:q], collection: handle_for_collection) do
            - if params[:product_type] && params[:product_type].include?(pt)
              .black-box-container
                .black-box-parent style='position: relative'
                  .black-box style='position: relative; top: 0; left: 0'
                  .small-black-box style='position: absolute; top: 0; left: 0'
                .sub-heading style='color: white' = pt
                .tick-icon
            - else
              .black-box-container
                .black-box
                .sub-heading style='color: white' = pt