config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  mount ShopifyApp::Engine, at: '/'
  resources :product_settings, only: [:update, :edit]
  resources :test_admins
  resources :test_proxies

  namespace :app_proxy do
    root action: 'index'
    get 'index', to: 'index'
  end

  get '/apps/products', as: :proxy_prod
  get '/app_proxy/index/:id', as: :collect_prod, to: 'app_proxy#index'

  get 'all_products', to: 'home#products', as: :all_products
  get '/products/sync', to: 'product_settings#sync', as: :sync_products

  get '/example', to: 'test_admins#example', as: :example

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/test_proxies_controller.rb
class TestProxiesController < ApplicationController
  def index
    if params[:filter].present?
      render_filtered_products
    elsif params[:search].present?
      render_searched_products
    else
      render_all_products
    end
  end

  private

  def render_all_products
    @products = ProductFilter.new(product_params).filter
    @vendor_array = Product.pluck(:vendor).uniq
    @size_array = ['L', 'M', 'S', "Women's", 'XL', 'XS', 'XXL', 'XXS']
    @product_type = Product.pluck(:product_type).uniq.reject(&:blank?)
    @price_ranges = ['0 - 31', '31 - 70', '71 - 90', '91 - 110']
    # render content_type: 'application/liquid'
  end

  def render_filtered_products
    page = params[:page]
    @products = ProductFilter.new(product_params).filter
    @products = [] if products_are_already_in_view?
    render json: {productsPartial: render_to_string('home/_products', locals: {showFirst: false}), layout: false, productCount: @products.count, lastProductID: @products.last.try(:id)}
  end

  def render_searched_products
    @products = ProductFilter.new({title: query_string}).search
    @popular = ProductFilter.new({title: query_string}).popular
    render json: {searchPartial: render_to_string('test_proxies/_search_results', layout: false) }
  end

  def product_params
    {limit: 36, title: params[:brand], product_type: params[:product_type], tag: params[:size], page: params[:page], price: params[:price], sort_by: params[:sort_by]}
  end

  def query_string
    synon = ProductSetting.last.product_synonyms.where('synonym = ?', params[:q]).first
    return params[:q] unless synon
    return synon.value
  end

  def products_are_already_in_view?
    params[:last_prod_id].present? && params[:last_prod_id] == @products.last.id.to_s rescue false
  end
end

app/views/test_proxies/_brand.html.slim
- if desktop
  .filter-brand-container.hidden-on-small-screen
    .heading-container
      .filter-brand-heading BRAND
      .js-brand-filter-icon.js-show-brand-filter
    .filter-brand-collection.js-brand-container
      - @vendor_array.each do |va|
        - brand = [va] << params[:brand]
        = link_to test_proxies_path(brand: brand.compact.flatten.uniq, size: params[:size], product_type: params[:product_type], price: params[:price]) do
          - if params[:brand] == va
            .black-box-container
              .black-box-parent style='position: relative'
                .black-box style='position: relative; top: 0; left: 0'
                .small-black-box style='position: absolute; top: 0; left: 0'
              .sub-heading = va
              .tick-icon
          - else
            .black-box-container
              .black-box
              .sub-heading = va
- else
  .filter-brand-container
    .heading-container
      .filter-brand-heading style='color: white' BRAND
      .js-brand-filter-icon.js-show-brand-filter
    .filter-brand-collection.js-brand-container
      - @vendor_array.each do |va|
        = link_to test_proxies_path(brand: va, size: params[:size], product_type: params[:product_type]) do
          - if params[:brand] == va
            .black-box-container
              .black-box-parent style='position: relative'
                .black-box style='position: relative; top: 0; left: 0'
                .small-black-box style='position: absolute; top: 0; left: 0'
              .sub-heading style='color: white' = va
              .tick-icon
          - else
            .black-box-container
              .black-box
              .sub-heading style='color: white' = va

app/views/test_proxies/_price.html.slim
- if desktop
  .filter-price-container.hidden-on-small-screen
    .heading-container
      .filter-price-heading PRICE
      .js-price-filter-icon.js-show-price-filter
    .filter-price-collection.js-price-container
      - @price_ranges.each do |pr|
        = link_to test_proxies_path(size: params[:size], brand: params[:brand], product_type: params[:product_type], price: pr) do
          - if params[:product_type] == pr
            .black-box-container
              .black-box-parent style='position: relative'
                .black-box style='position: relative; top: 0; left: 0'
                .small-black-box style='position: absolute; top: 0; left: 0'
              .sub-heading = "£ #{pr}"
              .tick-icon
          - else
            .black-box-container
              .black-box
              .sub-heading = "£ #{pr}"
- else
  .filter-price-container
    .heading-container
      .filter-price-heading style="color: white" PRICE
      .js-price-filter-icon.js-show-price-filter
    .filter-price-collection.js-price-container
      - @price_ranges.each do |pr|
        = link_to test_proxies_path(size: params[:size], brand: params[:brand], product_type: pr) do
          - if params[:product_type] == pr
            .black-box-container
              .black-box-parent style='position: relative'
                .black-box style='position: relative; top: 0; left: 0'
                .small-black-box style='position: absolute; top: 0; left: 0'
              .sub-heading style="color: white" = "£ #{pr}"
              .tick-icon
          - else
            .black-box-container
              .black-box
              .sub-heading style="color: white" = "£ #{pr}"

app/views/test_proxies/_search_results.html.slim
.search-result-main-container
  .search-result-product-container
    .search-result-product-text PRODUCTS
  div style="overflow: auto; background-color: red; height: 300px; width: 100%"
    - @products.each do |product|
      .search-result-container
        .search-result-image style="background-image: url('#{product.first_image_url}')"
        .search-result-sub-container
          .search-result-vendor style="font-weight: bold" = product.vendor
          .search-result-title  = truncate("#{product.title}", length: 45)
          .search-result-price  = "£ #{product.price} GBP"
  - if ProductSetting.last.related_search_on
    .search-result-product-container
      .search-result-product-text POPULAR SEARCHES
      br
      - @popular.each do |prod|
        p = prod.title

app/views/test_proxies/_size.html.slim
- if desktop
  .filter-size-container.hidden-on-small-screen
    .heading-container
      .filter-size-heading SIZE
      .js-size-filter-icon.js-show-size-filter
    .filter-size-collection.js-size-container
      - @size_array.each do |size|
        - multisize = [size] << params[:size]
        = link_to test_proxies_path(size: multisize.compact.flatten.uniq, brand: params[:brand], product_type: params[:product_type], price: params[:price]) do
          - if params[:size] == size
            .black-box-container
              .black-box-parent style='position: relative'
                .black-box style='position: relative; top: 0; left: 0'
                .small-black-box style='position: absolute; top: 0; left: 0'
              .sub-heading = size
              .tick-icon
          - else
            .black-box-container
              .black-box
              .sub-heading = size
- else
  .filter-size-container
    .heading-container
      .filter-size-heading style='color: white' SIZE
      .js-size-filter-icon.js-show-size-filter
    .filter-size-collection.js-size-container
      - @size_array.each do |size|
        = link_to test_proxies_path(size: size, brand: params[:brand], product_type: params[:product_type]) do
          - if params[:size] == size
            .black-box-container
              .black-box-parent style='position: relative'
                .black-box style='position: relative; top: 0; left: 0'
                .small-black-box style='position: absolute; top: 0; left: 0'
              .sub-heading style='color: white' = size
              .tick-icon
          - else
            .black-box-container
              .black-box
              .sub-heading  style='color: white' = size

app/views/test_proxies/_type.html.slim
- if desktop
  .filter-type-container.hidden-on-small-screen
    .heading-container
      .filter-type-heading TYPE
      .js-type-filter-icon.js-show-type-filter
    .filter-type-collection.js-type-container
      - @product_type.each do |pt|
        - prodtype = [pt] << params[:product_type]
        = link_to test_proxies_path(size: params[:size], brand: params[:brand], product_type: prodtype.compact.flatten.uniq, price: params[:price]) do
          - if params[:product_type] == pt
            .black-box-container
              .black-box-parent style='position: relative'
                .black-box style='position: relative; top: 0; left: 0'
                .small-black-box style='position: absolute; top: 0; left: 0'
              .sub-heading = pt
              .tick-icon
          - else
            .black-box-container
              .black-box
              .sub-heading = pt
- else
  .filter-type-container
    .heading-container
      .filter-type-heading style='color: white' TYPE
      .js-type-filter-icon.js-show-type-filter
    .filter-type-collection.js-type-container
      - @product_type.each do |pt|
        = link_to test_proxies_path(size: params[:size], brand: params[:brand], product_type: pt) do
          - if params[:product_type] == pt
            .black-box-container
              .black-box-parent style='position: relative'
                .black-box style='position: relative; top: 0; left: 0'
                .small-black-box style='position: absolute; top: 0; left: 0'
              .sub-heading style='color: white' = pt
              .tick-icon
          - else
            .black-box-container
              .black-box
              .sub-heading style='color: white' = pt

app/views/test_proxies/index.html.slim
.main-search.collapsed#main-search-id style="display: block"
  input placeholder="Search..." type="text" class="main-search-input"
  a.main-search-button
.js-search-results

.app-container
  #mySidenav.sidenav.hidden-on-large-screen
    div style='padding: 60px 16px'
      .close-filter-container
        .close-filter-text FILTER
        a.closebtn.hidden-on-large-screen style="font-size: 20px" href="javascript:void(0)" &times;

      - if params[:brand].present?
        = link_to test_proxies_path(size: params[:size], product_type: params[:product_type]) do
          .black-box-container
            .black-box-parent style='position: relative'
              .black-box style='position: relative; top: 0; left: 0'
              .small-black-box style='position: absolute; top: 0; left: 0'
            .sub-heading = params[:brand]
            .remove-filter

      - if params[:price].present?
        = link_to test_proxies_path(brand: params[:brand], product_type: params[:product_type], size: params[:size]) do
          .black-box-container
            .black-box-parent style='position: relative'
              .black-box style='position: relative; top: 0; left: 0'
              .small-black-box style='position: absolute; top: 0; left: 0'
            .sub-heading = params[:price]
            .remove-filter

      - if params[:size].present?
        = link_to test_proxies_path(brand: params[:brand], product_type: params[:product_type]) do
          .black-box-container
            .black-box-parent style='position: relative'
              .black-box style='position: relative; top: 0; left: 0'
              .small-black-box style='position: absolute; top: 0; left: 0'
            .sub-heading = "Size #{params[:size]}"
            .remove-filter

      - if params[:product_type].present?
        = link_to test_proxies_path(brand: params[:brand], size: params[:size]) do
          .black-box-container
            .black-box-parent style='position: relative'
              .black-box style='position: relative; top: 0; left: 0'
              .small-black-box style='position: absolute; top: 0; left: 0'
            .sub-heading = params[:product_type]
            .remove-filter

      - ProductSetting.last.filter_array.each do |filter|
        = render partial: filter, locals: {desktop: false}

  #myLeftSidenav.sidenav.hidden-on-large-screen
    div style='padding: 0 20px'
      .close-filter-container style='margin: 2rem 0 0 0'
        .close-filter-text SORT
        a.close-sort-btn.hidden-on-large-screen style="font-size: 20px" href="javascript:void(0)" &times;
      .sort-nav-container
        .black-box
        a href="#{test_proxies_url}" Sort
      .sort-nav-container
        .black-box
        a href="#{test_proxies_url(brand: params[:brand], size: params[:size], product_type: params[:product_type], sort_by: 'title_ascending')}" Alphabetically, A-Z
      .sort-nav-container
        .black-box
        a href="#{test_proxies_url(brand: params[:brand], size: params[:size], product_type: params[:product_type], sort_by: 'title_descending')}" Alphabetically, Z-A
      .sort-nav-container
        .black-box
        a href="#{test_proxies_url(brand: params[:brand], size: params[:size], product_type: params[:product_type], sort_by: 'price_ascending')}" Price, low to high
      .sort-nav-container
        .black-box
        a href="#{test_proxies_url(brand: params[:brand], size: params[:size], product_type: params[:product_type], sort_by: 'price_descending')}" Price, high to low
      .sort-nav-container
        .black-box
        a href="#{test_proxies_url(brand: params[:brand], size: params[:size], product_type: params[:product_type], sort_by: 'created_descending')}" Date, new to old
      .sort-nav-container
        .black-box
        a href="#{test_proxies_url(brand: params[:brand], size: params[:size], product_type: params[:product_type], sort_by: 'created_ascending')}" Date, old to new

  .openbtn-container.hidden-on-large-screen
    .openbtn-sub-container.hidden-on-large-screen.openbtn
      span.hidden-on-large-screen style="font-size:30px; cursor:pointer" FILTER

    .openbtn-sub-container.hidden-on-large-screen.open-sort-btn
      span.hidden-on-large-screen style="font-size:30px; cursor:pointer" SORT

  .filter-container.hidden-on-small-screen
    .filter-heading-container
      .filter-heading FILTER
      .js-main-filter-icon.js-show-main-filter
    select.select-style.hidden-on-small-screen onchange="window.location.href=this.value;"
      option value="#{test_proxies_url}" Sort
      / DOG SHIT
      - if params[:sort_by] == 'title_ascending'
        option selected='selected' value="#{test_proxies_url(brand: params[:brand], size: params[:size], product_type: params[:product_type], sort_by: 'title_ascending')} " Alphabetically, A-Z
      - else
        option value="#{test_proxies_url(brand: params[:brand], size: params[:size], product_type: params[:product_type], sort_by: 'title_ascending')} " Alphabetically, A-Z

      - if params[:sort_by] == 'price_ascending'
        option selected='selected' value="#{test_proxies_url(brand: params[:brand], size: params[:size], product_type: params[:product_type], sort_by: 'price_ascending')} " Price, low to high
      - else
        option value="#{test_proxies_url(brand: params[:brand], size: params[:size], product_type: params[:product_type], sort_by: 'price_ascending')} " Price, low to high


      - if params[:sort_by] == 'price_descending'
        option selected='selected' value="#{test_proxies_url(brand: params[:brand], size: params[:size], product_type: params[:product_type], sort_by: 'price_descending')} " Price, high to low
      - else
        option value="#{test_proxies_url(brand: params[:brand], size: params[:size], product_type: params[:product_type], sort_by: 'price_descending')} " Price, high to low


      - if params[:sort_by] == 'created_descending'
        option selected='selected' value="#{test_proxies_url(brand: params[:brand], size: params[:size], product_type: params[:product_type], sort_by: 'created_descending')} " Date, new to old
      - else
        option value="#{test_proxies_url(brand: params[:brand], size: params[:size], product_type: params[:product_type], sort_by: 'created_descending')} " Date, new to old


      - if params[:sort_by] == 'created_ascending'
        option selected='selected' value="#{test_proxies_url(brand: params[:brand], size: params[:size], product_type: params[:product_type], sort_by: 'created_ascending')} " Date, old to new
      - else
        option value="#{test_proxies_url(brand: params[:brand], size: params[:size], product_type: params[:product_type], sort_by: 'created_ascending')} " Date, old to new

  .main-container
    .filter-data-options-container.js-main-container.hidden-on-small-screen
      - if params[:brand].present?
        - params[:brand].each do |brand|
          - newbrand = params[:brand].dup
          - newbrand.delete(brand)
          = link_to test_proxies_path(size: params[:size], product_type: params[:product_type], price: params[:price], brand: newbrand) do
            .black-box-container
              .black-box-parent style='position: relative'
                .black-box style='position: relative; top: 0; left: 0'
                .small-black-box style='position: absolute; top: 0; left: 0'
              .sub-heading = brand
              .remove-filter

      - if params[:size].present?
        - params[:size].each do |size|
          - newSize = params[:size].dup
          - newSize.delete(size)
          = link_to test_proxies_path(brand: params[:brand], product_type: params[:product_type], price: params[:price], size: newSize) do
            .black-box-container
              .black-box-parent style='position: relative'
                .black-box style='position: relative; top: 0; left: 0'
                .small-black-box style='position: absolute; top: 0; left: 0'
              .sub-heading = "Size #{size}"
              .remove-filter

      - if params[:price].present?
        = link_to test_proxies_path(brand: params[:brand], product_type: params[:product_type], size: params[:size]) do
          .black-box-container
            .black-box-parent style='position: relative'
              .black-box style='position: relative; top: 0; left: 0'
              .small-black-box style='position: absolute; top: 0; left: 0'
            .sub-heading = params[:price]
            .remove-filter

      - if params[:product_type].present?
        - params[:product_type].each do |pt|
          - newpt = params[:product_type].dup
          - newpt.delete(pt)
          = link_to test_proxies_path(brand: params[:brand], size: params[:size], price: params[:price], product_type: newpt) do
            .black-box-container
              .black-box-parent style='position: relative'
                .black-box style='position: relative; top: 0; left: 0'
                .small-black-box style='position: absolute; top: 0; left: 0'
              .sub-heading = pt
              .remove-filter

      - ProductSetting.last.filter_array.each do |filter|
        = render partial: filter, locals: {desktop: true}

    .product-container
      .js-all-products
        = render partial: 'test_admins/products', locals: {showFirst: true}

    - if ProductSetting.last.autoscroll_on
      .gif-container
        .loading-gif.js-loading-gif style="background-image: url('#{ProductSetting.last.image.url}')"
    - else
      div style="width: 100%; text-align: center"
        = link_to ProductSetting.last.load_more_text, 'javascript:void(0)', class: 'js-load-more button', style: 'text-align: center;width: 397px;height: 56px;font-size: 20px;'

javascript:
  Window.paramUrl = "#{request.url.split("?")[1]}"
  Window.noOfProducts = "#{ProductSetting.last.number_of_items_to_load}"